version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3000:3000
    volumes:
      - ./config/:/app/config/

    environment:
      PUID: $PUID 
      PGID: $PGID
