version: '3'
services:
    adguardhome:
        image: adguard/adguardhome
        deploy:
            replicas: 3
        volumes:
            - adguardhome-work:/opt/adguardhome/work
            - adguardhome-config:/opt/adguardhome/conf
        ports:
            - 53:53/tcp
            - 53:53/udp
            - 68:68/udp
            - 80:80/tcp
            - 443:443/tcp
            - 443:443/udp
            - 3000:3000/tcp
volumes:
   adguardhome-work:
   adguardhome-config:
