---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets
version: '3.3'
- resources:
    cpu: true
    memory: true
    disk: /

- datetime:
    text_size: xl
    format:
      timeStyle: short
